language: node_js
node_js:
  - "0.12.1"
script: "npm run coverage"
after_script: "npm run coveralls"
env:
    global:
        - secure: "crKbyzN/w3hJWsUlyNcGy+Y252KV3Gb/RLHWQkY268MGSyIgdryZuD+VLG1daL75cLINmPz3qydAX7MKkNPP1NZL5YuW56hym78Qr1I8AfcHs8kXca2nAyuBFX4HlViF9idzWEnz3rfeSwg+ZOLWvvy6f+8MA0TszfjaXxXXenA="
